export const TYPE_ECOSYSTEM_TYPE = 'ECOSYSTEM_TYPE';
export const TYPE_LANGUAGE = 'LANGUAGE';
export const TYPE_LIVELIHOOD = 'LIVELIHOOD';
export const TYPE_COMMODITY = 'COMMODITY';
export const TYPE_ORGANIZATION = 'ORGANIZATION';
export const TYPE_AGRICULTURAL_PRODUCTION_METHOD =
  'AGRICULTURAL_PRODUCTION_METHOD';

export const ALL_TYPES = {
  ECOSYSTEM_TYPE: TYPE_ECOSYSTEM_TYPE,
  LANGUAGE: TYPE_LANGUAGE,
  LIVELIHOOD: TYPE_LIVELIHOOD,
  COMMODITY: TYPE_COMMODITY,
  ORGANIZATION: TYPE_ORGANIZATION,
  AGRICULTURAL_PRODUCTION_METHOD: TYPE_AGRICULTURAL_PRODUCTION_METHOD,
};
