export const TYPE_ECOSYSTEM_TYPE = 'ecosystem-type';
export const TYPE_LANGUAGE = 'language';
export const TYPE_LIVELIHOOD = 'livelihood';
export const TYPE_COMMODITY = 'commodity';
export const TYPE_ORGANIZATION = 'organization';
export const TYPE_AGRICULTURAL_PRODUCTION_METHOD =
  'agricultural-production-method';

export const ALL_TYPES = {
  ECOSYSTEM_TYPE: TYPE_ECOSYSTEM_TYPE,
  LANGUAGE: TYPE_LANGUAGE,
  LIVELIHOOD: TYPE_LIVELIHOOD,
  COMMODITY: TYPE_COMMODITY,
  ORGANIZATION: TYPE_ORGANIZATION,
  AGRICULTURAL_PRODUCTION_METHOD: TYPE_AGRICULTURAL_PRODUCTION_METHOD,
};
