export const PARTNERSHIP_STATUS_NO = 'no';
export const PARTNERSHIP_STATUS_IN_PROGRESS = 'in-progress';
export const PARTNERSHIP_STATUS_YES = 'yes';

export const ALL_PARTNERSHIP_STATUS = {
  NO: PARTNERSHIP_STATUS_NO,
  IN_PROGRESS: PARTNERSHIP_STATUS_IN_PROGRESS,
  YES: PARTNERSHIP_STATUS_YES,
};
